---
- name: Dell N-series Switch Backup and Firmware Update
  hosts: dell_switches
  gather_facts: false
  vars:
    backup_dir: "/backup/dell_switches"
    tftp_server: "192.168.1.100"
    firmware_file: "N1500_3.3.0.3.stk"
    firmware_path: "/tftpboot/{{ firmware_file }}"

  tasks:
    - name: Create backup directory if it doesn't exist
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Backup running configuration
      dellos6_command:
        commands:
          - show running-config
        provider: "{{ cli }}"
      register: running_config

    - name: Save running configuration to file
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}_config_{{ ansible_date_time.iso8601_basic }}.txt"
      delegate_to: localhost

    - name: Backup startup configuration
      dellos6_command:
        commands:
          - show startup-config
        provider: "{{ cli }}"
      register: startup_config

    - name: Save startup configuration to file
      copy:
        content: "{{ startup_config.stdout[0] }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}_startup_config_{{ ansible_date_time.iso8601_basic }}.txt"
      delegate_to: localhost

    - name: Check current firmware version
      dellos6_command:
        commands:
          - show version
        provider: "{{ cli }}"
      register: current_version

    - name: Display current firmware version
      debug:
        var: current_version.stdout[0]

    - name: Copy firmware from TFTP server
      dellos6_command:
        commands:
          - copy tftp://{{ tftp_server }}/{{ firmware_file }} image
        provider: "{{ cli }}"
      register: firmware_copy

    - name: Verify firmware copy
      dellos6_command:
        commands:
          - show bootvar
        provider: "{{ cli }}"
      register: bootvar_check

    - name: Display firmware copy status
      debug:
        var: firmware_copy.stdout[0]

    - name: Reload switch to apply new firmware
      dellos6_command:
        commands:
          - reload
        provider: "{{ cli }}"
      register: reload_output
      when: firmware_copy.stdout[0] is search("successful") 